### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by brudfors** [Project-MONAI/MetricsReloaded#1]
* Should the test script (`test_measures.py`) be runnable from the terminal? Currently, it requires modifications to run the tests defined in the functions.
* The following metrics are not being tested:
    * positive_likelihood_ratio
    * negative_predictive_values
    * boundary_iou
    * measured_hausdorff_distance
    * measured_hausdorff_distance_perc
    * net_benefit_treated
    * auroc
    * panoptic_quality
* Could scikit-learn be leveraged further for reference implementations?

**Comment by csudre** [comment]
Tests for Hausdorff distance have also been added so all metrics should now be tested. These tests use whenever possible one of the two Metrics Reloaded sister publications
