### ISSUE TITLE
Parallelize double for loops to speed up code

### ISSUE THREAD

**Issue by TobyUCL** [Project-MONAI/MetricsReloaded#17]
https://github.com/csudre/MetricsReloaded/blob/2895d959f847a3cd14b98ed0f49a6351e0181ae3/MetricsReloaded/utility/assignment_localization.py#L78-L80

These double for loops are possibly slowing down the code.

This could be speed up by parallelizaition. [Here](https://stackoverflow.com/questions/40450661/parallelize-these-nested-for-loops-in-python) is a possible solution.

This does solution does use two additional packages though. I know you would like to minimize the amount of packages to be downloaded.

**Comment by csudre** [comment]
This is not planned for now - may be in a future release
