### ISSUE TITLE
Hausdorff distance calculation does not match with other implementations

### ISSUE THREAD

**Issue by gasperpodobnik** [Project-MONAI/MetricsReloaded#41]
Hi, 
thank you for creating a single library with a comprehensive list of metrics. 

I'm looking at the `measured_distance` method that is used for Hausdorff distance calculation (https://github.com/Project-MONAI/MetricsReloaded/blob/0a0b4926796648cdf7fa152a7249eb20a1d6b2f0/MetricsReloaded/metrics/pairwise_measures.py#L1067). 
I do not understand why `[self.ref + self.pred > 0]` is used for indexing `ref_border_dist` and `pred_border_dist` in `hausdorff_distance_perc` calculation (which means that all distances that lie inside both binary masks are taken into account when computing the percentiles). I believe only surface distances should be used for the percentile calculation:
```
hausdorff_distance_perc = np.max(
    [
        np.percentile(ref_border_dist[pred_border.astype(bool)], q=perc),
        np.percentile(pred_border_dist[ref_border.astype(bool)], q=perc),
    ]
)
```

It would probably make more sense to update the `border_distance` method (https://github.com/Project-MONAI/MetricsReloaded/blob/0a0b4926796648cdf7fa152a7249eb20a1d6b2f0/MetricsReloaded/metrics/pairwise_measures.py#L1014), so that `distance_border_pred ` and `distance_border_ref` become vectors of border distances, 
```
distance_border_pred =  distance_pred[border_ref.astype(bool)]
distance_border_ref = distance_ref[border_pred.astype(bool)]
```
which removes the need for additional indexing when computing the percentiles in the `measured_distance` method.

**Comment by csudre** [comment]
Apologies for the mix-up - this is correct and while it does not matter for the maximum, the percentile should be taken only over the elements of the border. This has been corrected now.
